const String Index = "<!DOCTYPE html>"
"<html>"
"<head>"
"<title>Configuração station kate</title>"
"<meta charset = \"UTF-8\" >"
"<style>"
".input{"
"height: 80px;"
"color: white;"
"text-align: right;"
"font-family: 'Courier New', Courier, monospace;"
"font-size: 80px;"
"}"
".title{"
"font-family: 'Courier New', Courier, monospace;"
"color: white;"
"text-align: center;"
"padding-top: 5%;"
"}"
"input[type=submit] {"
"width: 80%;"
"background-color: #4CAF50;"
"color: white;"
"text-align: center;"
"padding: 14px 15px;"
"font-size: large;"
"margin: 8px 0;"
"border: none;"
"border-radius: 4px;"
"cursor: pointer;"
"font-family: 'Courier New', Courier, monospace;"
"}"
".radios{"
"width: 80%;"
"font-size: 40px;"
"float: left;"
"}"
"input[type=submit]:hover {"
"background-color: #45a049;"
"}"
".select{"
"padding: 0.7%;"
"color: black;"
"background-color: white;"
"width: 40%;"
"font-family: 'Courier New', Courier, monospace;"
"font-size: 40px;"
"height: 100px;"
"}"
".senha{"
"padding: 0.7%;"
"color: black;"
"background-color: white;"
"width: 40%;"
"font-family: 'Courier New', Courier, monospace;"
"font-size: 40px;"
"height: 100px;"
"}"
".radio{"
"color: white;"
"text-align: right;"
"font-family: 'Courier New', Courier, monospace;"
"font-size: 35px;"
"}"
".center{"
"text-align: center;"
"}"
"</style>"
"<script>"
"var xhr = new XMLHttpRequest();"
"xhr.addEventListener(\"readystatechange\", function() {"
"if(this.readyState === 4) {"
"console.log(this.responseText);"
"const obj = JSON.parse(this.responseText);"
"let redes = document.getElementById('redes');"
"for (const r of obj.redes) {"
"let opcao = document.createElement(\"option\");"
"opcao.value = r;"
"opcao.innerHTML = r;"
"redes.append(opcao)"
"}"
"}"
"});"
"xhr.open(\"GET\", \"/redes\");"
"xhr.send();"
"function opcao_id(id){"
"if(id == \"true\"){"
"let label = document.getElementById(\"label_ID\");"
"let h2_label = document.createElement(\"h2\");"
"h2_label.setAttribute(\"style\", \"padding: 0.3%;\");"
"let span_label = document.createElement(\"span\");"
"span_label.setAttribute(\"id\", \"span_label\");"
"h2_label.innerHTML = \"ID:\";"
"span_label.append(h2_label); "
"label.append(span_label);"
"let input_ID = document.getElementById(\"input_ID\");"
"let h2 = document.createElement(\"h2\");"
"let input = document.createElement(\"input\");"
"let span_ID = document.createElement(\"span\");"
"span_ID.setAttribute(\"id\", \"span_ID\");"
"input.setAttribute(\"title\", \"Identificador único que representa a estação.\");"
"input.setAttribute(\"style\", \"padding: 0.5%;\");"
"input.setAttribute(\"required\", \"required\");"
"input.setAttribute(\"type\", \"text\");"
"input.setAttribute(\"placeholder\", \"ID\");"
"input.setAttribute(\"name\", \"id\");"
"h2.append(input);"
"span_ID.append(h2);"
"input_ID.append(span_ID);"
"}else if(id == \"false\"){"
"document.getElementById(\"span_label\").remove();"
"document.getElementById(\"span_ID\").remove();"
"}"
"}"
"</script>"
"</head>"
"<body style = \"background-color: #502846\">"
"<h1 class=\"title\">Configuração estação Kate</h1>"
"<form action=\"/config\" method=\"post\">"
"<div class=\"input\" style=\"width: 100%; height: auto;text-align: center;padding-bottom: 40px;\">"

    "Rede<br>"
    "<select title=\"Nome da Rede Wifi a ser conectada.\" class= \"select\" required name=\"ssid\" id=\"redes\"><option value=\"\">Selecionar</option></select><br>"

    "Senha<br>"
    "<input title=\"Senha da rede.\" class = \"select\" type=\"password\" placeholder=\"Senha\" name=\"pass\" /><br>"

	"ID (vazio para o padrao)<br>"
    "<input title=\"ID da estacao.\" class = \"select\" type=\"ID\" placeholder=\"ID\" name=\"ID\" /><br>"

    "<div id=\"input_ID\"></div>"
    
"</div>"

"<span style=\"padding-left: 10%;\"><input type=\"submit\" value=\"Submeter\" style=\"height: 128px; font-size: 80px;\"></span>"
"</form>"
"</body>"
"</html>";

const String fail = "<!DOCTYPE html>"
"<head>"
"	<title>Confirmação</title>"
"</head>"
"<body>"
"	<h1 style=\"text-align:center; padding-top: 20%;\">"
"		FALHA"
"	</h1>"
"	<a href=\"/\"> voltar </a>"
"</body>"
"</html>";

const String success = "<!DOCTYPE html>"
"<head>"
"	<title>Confirmação</title>"
"</head>"
"<body>"
"	<h1 style=\"text-align:center; padding-top: 20%;\">"
"		CONFIRMADO COM SUCESSO"
"	</h1>"
"	<a href=\"/\"> voltar </a>"
"</body>"
"</html>";

